#!/usr/bin/env node
import { existsSync, readFileSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

const args = process.argv.slice(2);
const value = (flag, fallback) => { const index = args.indexOf(flag); return index === -1 ? fallback : args[index + 1] ?? fallback; };
const has = (flag) => args.includes(flag);

const OWNERSHIP = "// Generated by userr. Safe to edit; `userr upgrade` never overwrites a changed file.\n";

function usage() {
  console.log("Usage: userr <init|add|doctor|upgrade> [--backend convex|neon] [--framework next] [--dry-run] [--cwd path]");
}

function detect(root) {
  const packagePath = join(root, "package.json");
  const packageJson = existsSync(packagePath) ? JSON.parse(readFileSync(packagePath, "utf8")) : null;
  const dependencies = { ...(packageJson?.dependencies ?? {}), ...(packageJson?.devDependencies ?? {}) };
  return { hasPackage: Boolean(packageJson), next: Boolean(dependencies.next || existsSync(join(root, "app"))), convex: Boolean(dependencies.convex || existsSync(join(root, "convex"))) };
}

function filesFor({ backend, framework }) {
  if (backend !== "convex" && backend !== "neon") throw new Error(`Backend '${backend}' is unknown. Available: convex, neon.`);
  if (framework !== "next") throw new Error(`Framework '${framework}' is planned but not installable yet. Available: next.`);
  // init owns project setup only (config + manifest + guide). Portal pages
  // belong to `add`: sharing the page path between commands turned init's
  // placeholder into an unresolvable conflict.
  const backendNotes =
    backend === "convex"
      ? "Add the Convex component to `convex/convex.config.ts`, create authenticated host wrappers, then run `userr add --backend convex` for the portal pages."
      : "Install @userr/neon, drizzle-orm and pg, apply the migrations to your Postgres database, wire identify/resolveRole to your auth, then run `userr add --backend neon` for the portal pages and API route.";
  return {
    "userr.config.ts": `export default {\n  backend: "${backend}",\n  boardSlug: "feedback",\n  portalPath: "/feedback",\n  adminPath: "/admin/feedback",\n};\n`,
    ".userr/README.md": `# Userr\n\nGenerated files are safe to edit. ${backendNotes}\n`,
  };
}

function convexBoardImports() {
  return `import { BoardList, FeedbackProvider, SubmitDialog } from "@userr/react";\nimport { useConvexItems } from "@userr/react/convex";\n`;
}

function boardPage({ backend }) {
  const dataHook =
    backend === "convex"
      ? `// TODO: import your generated bindings, e.g. \`import { api } from "@/convex/_generated/api";\`\n  const BOARD_ID = "TODO-board-id" as never;\n  const { items, status, loadMore } = useConvexItems(api.items.list as never, { boardId: BOARD_ID });`
      : `import { createRestClient } from "@userr/react/rest";\nconst client = createRestClient({ baseUrl: "/api/userr" });\n  // TODO: fetch with SWR/React Query, e.g. useSWR(["items", boardSlug], () => client.listItems({ boardId: boardSlug }));\n  const items: never[] = [];`;
  return `${OWNERSHIP}"use client";\n${backend === "convex" ? convexBoardImports() : `import { BoardList, FeedbackProvider, SubmitDialog } from "@userr/react";\n`}\n// TODO: resolve your board (by slug via getBySlug) and wire create/vote mutations.\nexport default function FeedbackBoardPage() {\n  ${dataHook}\n  void loadMore;\n  return <FeedbackProvider><main>\n    <SubmitDialog onSubmit={async () => { throw new Error("Wire onSubmit to your create mutation."); }} />\n    <BoardList items={items as never} hasMore={status !== "Exhausted"} />\n  </main></FeedbackProvider>;\n}\n`;
}

function detailPage({ backend }) {
  void backend;
  return `${OWNERSHIP}"use client";\nimport { FeedbackProvider, ItemDetail } from "@userr/react";\n\n// TODO: load the item by slug (Convex: api.items.get; Neon: client.getItem) plus comments, votes, and subscriptions.\nexport default function FeedbackDetailPage() {\n  return <FeedbackProvider><main>{/* <ItemDetail item={item} comments={comments} /> */}</main></FeedbackProvider>;\n}\n`;
}

function roadmapPage({ backend }) {
  void backend;
  return `${OWNERSHIP}"use client";\nimport { FeedbackProvider, RoadmapBoard } from "@userr/react";\n\n// TODO: load lanes (Convex: api.roadmap.list; Neon: client.listLanes) and group items per lane states.\nexport default function RoadmapPage() {\n  return <FeedbackProvider><main>{/* <RoadmapBoard lanes={lanes} itemsByLane={itemsByLane} /> */}</main></FeedbackProvider>;\n}\n`;
}

function changelogPages() {
  return {
    "app/changelog/page.tsx": `${OWNERSHIP}"use client";\nimport { FeedbackProvider, ChangelogList } from "@userr/react";\n\n// TODO: load entries (Convex: api.changelog.list; Neon: client.listChangelog).\nexport default function ChangelogPage() {\n  return <FeedbackProvider><main>{/* <ChangelogList entries={entries} /> */}</main></FeedbackProvider>;\n}\n`,
    "app/changelog/[slug]/page.tsx": `${OWNERSHIP}import { ChangelogEntry } from "@userr/react";\n\n// TODO: load one entry by slug (Convex: api.changelog.getBySlug; Neon: direct query).\nexport default function ChangelogEntryPage() {\n  return <main>{/* <ChangelogEntry entry={entry} /> */}</main>;\n}\n`,
  };
}

function rssRoute({ backend }) {
  const source =
    backend === "convex"
      ? `// TODO: set NEXT_PUBLIC_CONVEX_URL and import { api } from "@/convex/_generated/api";\n  // Only expose public boards here; gate private boards behind your auth.\n  const { ConvexHttpClient } = await import("convex/browser");\n  const client = new ConvexHttpClient(process.env.NEXT_PUBLIC_CONVEX_URL!);\n  const { page } = await client.query("changelog:list" as never, { boardId: "TODO-board-id", paginationOpts: { numItems: 20, cursor: null } } as never) as never as { page: { title: string; slug: string; body: string; publishedAt?: number }[] };`
      : `// TODO: query published entries via @userr/neon listChangelog with your DATABASE_URL pool.\n  // Only expose public boards here; gate private boards behind your auth.\n  const page: { title: string; slug: string; body: string; publishedAt?: number }[] = [];`;
  return `${OWNERSHIP}// XML-escape titles: a literal "]]>" inside CDATA would terminate the section\n// and corrupt or inject XML into the feed. Slugs are path-encoded below.\nfunction cdata(text) {\n  return String(text ?? "").replaceAll("]]>", "]]&gt;");\n}\nexport async function GET() {\n  ${source}\n  const items = page.map((e) => \`    <item><title><![CDATA[\${cdata(e.title)}]]></title><link>/changelog/\${encodeURIComponent(e.slug)}</link><pubDate>\${new Date(e.publishedAt ?? Date.now()).toUTCString()}</pubDate></item>\`).join("\\n");\n  const xml = \`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Changelog</title>\${items}</channel></rss>\`;\n  return new Response(xml, { headers: { "content-type": "application/rss+xml" } });\n}\n`;
}

function neonApiRoute() {
  return `${OWNERSHIP}import { Pool } from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { toNextJsHandler } from "@userr/neon/handler";
import * as schema from "@userr/neon/schema";

// TODO: install pg + drizzle-orm, set DATABASE_URL, and wire identify to your
// auth (session cookie, JWT, or API key). SECURITY: never trust a client-sent
// header or body field as the actor ID — any visitor could impersonate another
// user. This scaffold refuses all writes until you replace the stub below.
const pool = new Pool({ connectionString: process.env.DATABASE_URL! });
const db = drizzle(pool, { schema });

export const { GET, POST, PATCH, DELETE } = toNextJsHandler({
  db,
  identify: async () => {
    throw new Error(
      "Wire identify to your auth (e.g. read your session cookie and return the user ID).",
    );
  },
});
`;
}

function filesForAdd({ backend, framework }) {
  if (framework !== "next") throw new Error(`Framework '${framework}' is planned but not installable yet. Available: next.`);
  if (backend !== "convex" && backend !== "neon") throw new Error(`Backend '${backend}' is unknown. Available: convex, neon.`);
  const files = {
    "app/feedback/page.tsx": boardPage({ backend }),
    "app/feedback/[slug]/page.tsx": detailPage({ backend }),
    "app/roadmap/page.tsx": roadmapPage({ backend }),
    ...changelogPages(),
    "app/changelog/rss/route.ts": rssRoute({ backend }),
  };
  if (backend === "neon") {
    files["app/api/userr/[...path]/route.ts"] = neonApiRoute();
  }
  files["app/sitemap.ts"] = sitemapFile({ backend });
  return files;
}

function sitemapFile({ backend }) {
  const source =
    backend === "convex"
      ? `// TODO: import { api } from "@/convex/_generated/api" and list boards, items, and changelog entries.\n  // Only include public boards; gate private content behind your auth.\n  return [];`
      : `// TODO: query boards, items, and changelog entries via @userr/neon with your DATABASE_URL pool.\n  // Only include public boards; gate private content behind your auth.\n  return [];`;
  return `${OWNERSHIP}import type { MetadataRoute } from "next";\n\nexport default async function sitemap(): Promise<MetadataRoute.Sitemap> {\n  ${source}\n}\n`;
}

function readManifest(root) {
  const path = join(root, ".userr", "manifest.json");
  if (!existsSync(path)) return null;
  try { return JSON.parse(readFileSync(path, "utf8")); } catch { return null; }
}

async function writeFiles(root, files, { dryRun, meta = {} }) {
  const manifest = readManifest(root);
  const known = new Set(manifest?.files ?? []);
  for (const [relative, content] of Object.entries(files)) {
    const target = join(root, relative); const current = existsSync(target) ? readFileSync(target, "utf8") : null;
    const action = current === content ? "unchanged" : current === null ? "create" : "conflict";
    console.log(`${action.padEnd(9)} ${relative}`);
    if (!dryRun && action === "create") { await mkdir(dirname(target), { recursive: true }); await writeFile(target, content, "utf8"); }
    known.add(relative);
  }
  if (!dryRun) { await mkdir(join(root, ".userr"), { recursive: true }); await writeFile(join(root, ".userr", "manifest.json"), JSON.stringify({ version: 1, ...manifest, ...meta, files: [...known] }, null, 2) + "\n"); }
  console.log(dryRun ? "No files were written." : "Generated files written. Existing files were never overwritten.");
}

async function init() {
  const root = resolve(value("--cwd", process.cwd())); const backend = value("--backend", "convex"); const framework = value("--framework", "next"); const dryRun = has("--dry-run");
  const detected = detect(root); const files = filesFor({ backend, framework });
  if (!detected.hasPackage) throw new Error(`No package.json found in ${root}. Run inside an application project.`);
  console.log(`Userr: ${backend} + ${framework}${dryRun ? " (dry run)" : ""}`);
  console.log(`Detected: Next=${detected.next}, Convex=${detected.convex}`);
  await writeFiles(root, files, { dryRun, meta: { backend, framework } });
}

async function add() {
  const root = resolve(value("--cwd", process.cwd())); const backend = value("--backend", "convex"); const framework = value("--framework", "next"); const dryRun = has("--dry-run");
  const detected = detect(root); const files = filesForAdd({ backend, framework });
  if (!detected.hasPackage) throw new Error(`No package.json found in ${root}. Run inside an application project.`);
  if (!detected.next) throw new Error(`No Next.js project detected in ${root}. 'add' scaffolds App Router pages.`);
  console.log(`Userr add: ${backend} + ${framework}${dryRun ? " (dry run)" : ""}`);
  await writeFiles(root, files, { dryRun, meta: { backend, framework } });
}

function doctor() {
  const root = resolve(value("--cwd", process.cwd())); const detected = detect(root);
  if (!detected.hasPackage) throw new Error(`No package.json found in ${root}.`);
  const manifest = readManifest(root);
  const backend = manifest?.backend ?? value("--backend", "convex");
  const packageJson = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
  const dependencies = { ...(packageJson?.dependencies ?? {}), ...(packageJson?.devDependencies ?? {}) };
  const checks = [["Next.js project", detected.next]];
  if (backend === "convex") {
    checks.push(["Convex installed", detected.convex]);
  } else {
    checks.push(["@userr/neon installed", Boolean(dependencies["@userr/neon"])]);
    checks.push(["API route generated", existsSync(join(root, "app", "api", "userr", "[...path]", "route.ts"))]);
  }
  checks.push(["userr.config.ts", existsSync(join(root, "userr.config.ts"))]);
  checks.push(["generated manifest", manifest !== null]);
  let ok = true;
  for (const [name, passed] of checks) { console.log(`${passed ? "✓" : "✗"} ${name}`); if (!passed) ok = false; }
  if (backend !== "convex" && !process.env.DATABASE_URL) {
    console.log("! DATABASE_URL is not set in this environment (needed at runtime; .env.local is fine).");
  }
  if (!ok) process.exitCode = 1;
}

async function upgrade() {
  console.log("Upgrade uses the installer’s non-overwrite policy.");
  await init();
}

if (!args[0] || has("--help")) usage();
else if (args[0] === "init") init().catch((error) => { console.error(`Error: ${error.message}`); process.exitCode = 1; });
else if (args[0] === "add") add().catch((error) => { console.error(`Error: ${error.message}`); process.exitCode = 1; });
else if (args[0] === "doctor") { try { doctor(); } catch (error) { console.error(`Error: ${error.message}`); process.exitCode = 1; } }
else if (args[0] === "upgrade") upgrade().catch((error) => { console.error(`Error: ${error.message}`); process.exitCode = 1; });
else { usage(); process.exitCode = 1; }
